version: '3.9'

services:
  db:
    container_name: postgres
    restart: unless-stopped
    image: postgres:16.3-alpine3.20
    ports:
      - "5432:5432"
    volumes:
      - ./postgres/scripts:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=gwintdb

  app:
    build: .
    container_name: app
    ports:
      - "12345:12345"
    env_file:
      - .env
    depends_on:
      db:
        condition: service_started

networks:
  default:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.enable_ip_masquerade: "true"
      com.docker.network.driver.mtu: "1500"
      com.docker.network.bridge.enable_icc: "true"
